services:
  postgres:
    image: postgres:18
    container_name: ratfy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ratfy
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
  mailpit:
    image: axllent/mailpit
    container_name: ratfy-mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  postgres_data:
  mailpit_data:
