-- AlterTable: Album - add missing fields
ALTER TABLE "Album" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Album" ADD COLUMN IF NOT EXISTS "isPublic" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Album" ADD COLUMN IF NOT EXISTS "coverImageKey" TEXT;
ALTER TABLE "Album" ADD COLUMN IF NOT EXISTS "coverImageSize" INTEGER;

-- AlterTable: Artist - add profile image fields
ALTER TABLE "Artist" ADD COLUMN IF NOT EXISTS "profileImageKey" TEXT;
ALTER TABLE "Artist" ADD COLUMN IF NOT EXISTS "profileImageSize" INTEGER;

-- AlterTable: Playlist - add cover image fields
ALTER TABLE "Playlist" ADD COLUMN IF NOT EXISTS "coverImageKey" TEXT;
ALTER TABLE "Playlist" ADD COLUMN IF NOT EXISTS "coverImageSize" INTEGER;

-- AlterTable: Track - rename title to name, add missing + storage fields
ALTER TABLE "Track" RENAME COLUMN "title" TO "name";
ALTER TABLE "Track" ADD COLUMN IF NOT EXISTS "artistIds" TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE "Track" ADD COLUMN IF NOT EXISTS "externalIds" JSONB;
ALTER TABLE "Track" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Track" ADD COLUMN IF NOT EXISTS "isLocal" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Track" ADD COLUMN IF NOT EXISTS "isPublic" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Track" ADD COLUMN IF NOT EXISTS "popularity" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Track" ADD COLUMN IF NOT EXISTS "audioFileKey" TEXT;
ALTER TABLE "Track" ADD COLUMN IF NOT EXISTS "audioFileSize" INTEGER;
ALTER TABLE "Track" ADD COLUMN IF NOT EXISTS "audioContentType" TEXT;
ALTER TABLE "Track" ADD COLUMN IF NOT EXISTS "drmEnabled" BOOLEAN NOT NULL DEFAULT false;
